
##################
# Basic Settings #
##################

# 
#  (Life Rate)    x      (Reduction factor)      = (Slowed Rate)
#  (24frames/1s)  x  (1s/10min)  x  (1min/60s)   = (0.04 frame/s)
#
#   Delay = 1 / (24 / (1 / 600)) = 25s
#

# watch -n1 /opt/vc/bin/vcgencmd measure_temp

# The following was for software encoding, prior to using a HW encoding codec.
#
# +-----------------------------------------------------------------------------+-----------
# | HW      | Camera | Resolution | Pixels | fr/seg | create_video() | append() |  pixels/s |
# +-----------------------------------------------------------------------------+-----------
# | Pi0     | v1.3   |  640x480   | 0.31M  |   10   | 19s    (0.3m)  | 1s       |  0.16M/s  |
# | Pi0     | v1.3   |  640x480   | 0.31M  |   20   | 37s    (0.6m)  | 1s       |  0.17M/s  |
# | Pi0     | v1.3   |  1024x768  | 0.79M  |   10   | 52s    (0.9m)  | 2s       |  0.15M/s  |
# | Pi0     | v1.3   |  1024x768  | 0.79M  |   20   | 98s    (1.7m)  | 2s       |  0.16M/s  |
# | Pi0     | v1.3   |  1296x972  | 1.26M  |   10   | 80s    (1.3m)  | 2s       |  0.16M/s  |
# | Pi0     | v1.3   |  1296x972  | 1.26M  |   20   | 191s   (3.2m)  | 2s       |  0.13M/s  |
# | Pi0     | v1.3   |  2592x1944 | 5.03M  |   10   | 450s   (7.5m)  | 6s       |  0.11M/s  |
# | Pi0     | v1.3   |  2592x1944 | 5.03M  |   20   |                |          |           |
# +-----------------------------------------------------------------------------+----------+

#########################
# GENERAL VIDEO OPTIONS
#########################

# Image resolution Set to empty object (`{ }`) to use default resolution.
resolution:
##### 4:3 #####
#  width: 640
#  height: 480
#  width: 1024
#  height: 768
#  width: 1296
#  height: 972
#  width: 1600
#  height: 1200
  width: 2592
  height: 1944
##### 16:7 #####
#  width: 1920
#  height: 1080
#  width: 2560
#  height: 1440





# The interval between captures (in seconds). (float OK)
interval: 20

# frames per segment
segment_size: 30

#########################
# GIF OPTIONS
#########################

# Whether to create an gif after capturing the time-lapse images.
create_gif: False

#########################
# MPEG ENCODING OPTIONS
#########################
# See https://trac.ffmpeg.org/wiki/Encode/H.264 for more information

# Whether to create an video after capturing the time-lapse images.
create_video: True

# Output video's frame rate
frame_rate: 25

# HW Codec only seems to support 4:3


# Specifies the encoding output to a specific H.264 profile
# Options: baseline, main, high, high10, high422, high444
video_profile: baseline

# A preset is a collection of options that will provide a certain encoding speed to compression ratio. A slower preset
# will provide better compression (compression is quality per filesize).
# Options: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
video_preset:  veryfast

hq_frame_rate: 24
hq_video_profile: baseline 
hq_video_preset: veryfast

# Filename of created video
output_filename: timelapse.mp4

#####################
# Advanced settings #
#####################

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 0

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 0

# White balance. Set to empty object (`{ }`) to use auto white balance.
white_balance: { }
  # red_gain: 1.3
  # blue_gain: 1.75

# Rotate the images taken by the camera. Possible value are 0, 90, 180 or 270
rotation: 90

#############################
# Power/heat saving options #                   
#############################

# Disabling HDMI can save about 25mA
# https://www.jeffgeerling.com/blogs/jeff-geerling/raspberry-pi-zero-conserve-energy
disable_hdmi: True

# Disabling LEDs can save about 5mA per LED
# https://www.jeffgeerling.com/blogs/jeff-geerling/raspberry-pi-zero-conserve-energy
disable_pi_leds: True

# The v1 camera has an LED that can be disabed.
# Requires that RPi.GPIO package installed, and the Python capture process is running with
# sufficient privileges (typically this means running as root with sudo python)
disable_camera_led: True

# Diretories for files
video_path: /home/pi/work/pilapse/videos
gif_path:   /home/pi/work/pilapse/gifs
image_path: /home/pi/work/pilapse/images
